# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [ ]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [ ]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

In [ ]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [ ]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [ ]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [3]:
# Question 1
# open and load json using file path
json.load(open('data/world_bank_projects.json'))
# read json file to pandas dataframe
json_df = pd.read_json('data/world_bank_projects.json')
# access countryname value counts and print the top 10
print(json_df.countryname.value_counts().head(10))

People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Kingdom of Morocco                 12
People's Republic of Bangladesh    12
Nepal                              12
Republic of Mozambique             11
Africa                             11
Name: countryname, dtype: int64

In [10]:
# Question 2
# load json to projects as list
projects=json.load((open('data/world_bank_projects.json')))
# create dataframe where each row is individual project theme using json_normalize
mjthemes=json_normalize(projects,'mjtheme_namecode')
# create variable code counts that has total instances of each theme code next the code
codecounts=mjthemes['code'].value_counts()
codecounts

11    250
10    216
8     210
2     199
6     168
4     146
7     130
5      77
9      50
1      38
3      15
Name: code, dtype: int64

In [16]:
# Question 3
# Create dataframe of codes with corresponding names
themecodes = mjthemes[mjthemes['name'] != ''].drop_duplicates()

# Perform inner join of mjthemes and themecodes on 'code' column 
filled = mjthemes.merge(themecodes, on='code', how='inner')
# drop name_x (ie original mjthemes name column)
filled = filled.drop(columns='name_x')
# rename columns
filled.columns = ['code', 'name']
filled

     code               name
0       8  Human development
1       8  Human development
2       8  Human development
3       8  Human development
4       8  Human development
5       8  Human development
6       8  Human development
7       8  Human development
8       8  Human development
9       8  Human development
10      8  Human development
11      8  Human development
12      8  Human development
13      8  Human development
14      8  Human development
15      8  Human development
16      8  Human development
17      8  Human development
18      8  Human development
19      8  Human development
20      8  Human development
21      8  Human development
22      8  Human development
23      8  Human development
24      8  Human development
25      8  Human development
26      8  Human development
27      8  Human development
28      8  Human development
29      8  Human development
...   ...                ...
1469    9  Urban development
1470    9  Urban development
1471    9  Urban development
1472    9  Urban development
1473    9  Urban development
1474    9  Urban development
1475    9  Urban development
1476    9  Urban development
1477    9  Urban development
1478    9  Urban development
1479    9  Urban development
1480    9  Urban development
1481    9  Urban development
1482    9  Urban development
1483    9  Urban development
1484    3        Rule of law
1485    3        Rule of law
1486    3        Rule of law
1487    3        Rule of law
1488    3        Rule of law
1489    3        Rule of law
1490    3        Rule of law
1491    3        Rule of law
1492    3        Rule of law
1493    3        Rule of law
1494    3        Rule of law
1495    3        Rule of law
1496    3        Rule of law
1497    3        Rule of law
1498    3        Rule of law

[1499 rows x 2 columns]

In [14]:
filled.columns[1]

'name_y'